// ANIMAL KING TOURNAMENT DATABASE
// Validated Animals (Image Exists)
// Generated by filter_animals_v2.ps1

const DIGIMON_DATABASE = [
    { id: 1, name: "African Lion", type: "fire", typeLabel: "Beast", image: "images/African_Lion.jpg", stats: { hp: 100, attack: 35, defense: 20, speed: 22 }, skills: [ {name:"King's Roar", damage:20, type:"normal"}, {name:"Pride Assault", damage:30, type:"fire"}, {name:"Neck Bite", damage:50, type:"fire"} ] },
    { id: 2, name: "Bengal Tiger", type: "fire", typeLabel: "Beast", image: "images/Bengal_Tiger.jpg", stats: { hp: 100, attack: 38, defense: 18, speed: 24 }, skills: [ {name:"Ambush", damage:20, type:"normal"}, {name:"Jungle Fury", damage:30, type:"fire"}, {name:"Tiger Claw", damage:50, type:"fire"} ] },
    { id: 3, name: "Komodo Dragon", type: "fire", typeLabel: "Reptile", image: "images/Komodo_Dragon.jpg", stats: { hp: 100, attack: 32, defense: 22, speed: 18 }, skills: [ {name:"Venom Bite", damage:20, type:"normal"}, {name:"Tail Whip", damage:30, type:"fire"}, {name:"Bacteria Infect", damage:50, type:"fire"} ] },
    { id: 4, name: "Leopard", type: "fire", typeLabel: "Beast", image: "images/Leopard.jpg", stats: { hp: 100, attack: 30, defense: 16, speed: 28 }, skills: [ {name:"Tree Ambush", damage:20, type:"normal"}, {name:"Claw Slash", damage:30, type:"fire"}, {name:"Predator Instinct", damage:50, type:"fire"} ] },
    { id: 5, name: "Wolverine", type: "fire", typeLabel: "Beast", image: "images/Wolverine.jpg", stats: { hp: 100, attack: 28, defense: 28, speed: 20 }, skills: [ {name:"Snow Pounce", damage:20, type:"normal"}, {name:"Vicious Claw", damage:30, type:"fire"}, {name:"Berserk", damage:50, type:"fire"} ] },
    { id: 6, name: "Great White Shark", type: "water", typeLabel: "Ocean", image: "images/Great_White_Shark.jpg", stats: { hp: 100, attack: 42, defense: 20, speed: 25 }, skills: [ {name:"Fin Strike", damage:20, type:"normal"}, {name:"Deep Bite", damage:30, type:"water"}, {name:"Feeding Frenzy", damage:50, type:"water"} ] },
    { id: 7, name: "Orca", type: "water", typeLabel: "Ocean", image: "images/Orca.jpg", stats: { hp: 100, attack: 45, defense: 25, speed: 22 }, skills: [ {name:"Pod Hunt", damage:20, type:"normal"}, {name:"Tail Slap", damage:30, type:"water"}, {name:"Apex Dive", damage:50, type:"water"} ] },
    { id: 8, name: "Blue Whale", type: "water", typeLabel: "Ocean", image: "images/Blue_Whale.jpg", stats: { hp: 100, attack: 50, defense: 40, speed: 10 }, skills: [ {name:"Tail Smash", damage:20, type:"normal"}, {name:"Ocean Song", damage:30, type:"water"}, {name:"Tsunami Breach", damage:50, type:"water"} ] },
    { id: 9, name: "African Elephant", type: "nature", typeLabel: "Giant", image: "images/African_Elephant.jpg", stats: { hp: 100, attack: 45, defense: 35, speed: 15 }, skills: [ {name:"Trunk Slam", damage:20, type:"normal"}, {name:"Tusk Gore", damage:30, type:"nature"}, {name:"Stampede", damage:50, type:"nature"} ] },
    { id: 10, name: "Moose", type: "nature", typeLabel: "Giant", image: "images/Moose.jpg", stats: { hp: 100, attack: 30, defense: 25, speed: 22 }, skills: [ {name:"Antler Ram", damage:20, type:"normal"}, {name:"Forest Dash", damage:30, type:"nature"}, {name:"Giant Kick", damage:50, type:"nature"} ] },
    { id: 11, name: "Golden Eagle", type: "light", typeLabel: "Bird", image: "images/Golden_Eagle.jpg", stats: { hp: 100, attack: 32, defense: 15, speed: 35 }, skills: [ {name:"Talon Grip", damage:20, type:"normal"}, {name:"Sky Dive", damage:30, type:"light"}, {name:"Golden Strike", damage:50, type:"light"} ] },
    { id: 12, name: "Peacock", type: "light", typeLabel: "Bird", image: "images/Peacock.jpg", stats: { hp: 100, attack: 20, defense: 15, speed: 22 }, skills: [ {name:"Fan Display", damage:20, type:"normal"}, {name:"Beak Peck", damage:30, type:"light"}, {name:"Mystic Eye", damage:50, type:"light"} ] },
    { id: 13, name: "Ostrich", type: "light", typeLabel: "Bird", image: "images/Ostrich.jpg", stats: { hp: 100, attack: 30, defense: 18, speed: 38 }, skills: [ {name:"Mega Kick", damage:20, type:"normal"}, {name:"Sprint", damage:30, type:"light"}, {name:"Beak Strike", damage:50, type:"light"} ] },
    { id: 14, name: "Albatross", type: "light", typeLabel: "Bird", image: "images/Albatross.jpg", stats: { hp: 100, attack: 22, defense: 18, speed: 25 }, skills: [ {name:"Ocean Glide", damage:20, type:"normal"}, {name:"Wing Slap", damage:30, type:"light"}, {name:"Global Roam", damage:50, type:"light"} ] },
    { id: 15, name: "King Cobra", type: "dark", typeLabel: "Reptile", image: "images/King_Cobra.jpg", stats: { hp: 100, attack: 35, defense: 10, speed: 30 }, skills: [ {name:"Venom Spit", damage:20, type:"normal"}, {name:"Hood Flare", damage:30, type:"dark"}, {name:"Neurotoxin", damage:50, type:"dark"} ] },
    { id: 16, name: "Tarantula", type: "dark", typeLabel: "Insect", image: "images/Tarantula.jpg", stats: { hp: 100, attack: 28, defense: 15, speed: 25 }, skills: [ {name:"Fang Bite", damage:20, type:"normal"}, {name:"Hair Flick", damage:30, type:"dark"}, {name:"Spider Venom", damage:50, type:"dark"} ] },
    { id: 17, name: "Fire Dragon (KD)", type: "fire", typeLabel: "Reptile", image: "images/fire_dragon.jpg", stats: { hp: 100, attack: 32, defense: 20, speed: 20 }, skills: [ {name:"Bite", damage:20, type:"normal"}, {name:"Claw", damage:30, type:"fire"}, {name:"Inferno", damage:50, type:"fire"} ] },
    { id: 18, name: "Mega T-Rex", type: "fire", typeLabel: "Dino", image: "images/mega_dragon.jpg", stats: { hp: 100, attack: 50, defense: 30, speed: 15 }, skills: [ {name:"Chomp", damage:20, type:"normal"}, {name:"Roar", damage:30, type:"fire"}, {name:"Jurassic Crush", damage:50, type:"fire"} ] },
];

// Type Effectiveness Chart
const TYPE_EFFECTIVENESS = {
    fire: { strong: ['nature'], weak: ['water'] },
    water: { strong: ['fire'], weak: ['nature'] },
    nature: { strong: ['water'], weak: ['fire'] },
    light: { strong: ['dark'], weak: ['dark'] },
    dark: { strong: ['light'], weak: ['light'] },
    neutral: { strong: [], weak: [] }
};
